### PR TITLE
Add sorting by creation date option

### PR DESCRIPTION
**Pull request by beliaev-maksim**
add the possibility to sort by creation date. This is useful to see if the spec was created a while ago and still is not completed

### CODE REVIEW

**Review by anthonydillon — APPROVED** [review]
Code and QA works :+1: _we should improve the tests in a follow up soon_

**Comment by beliaev-maksim** [comment]
@anthonydillon I am not sure, I do manual testing now. It does sorting indeed, but I am not sure how the data is aggregated in the backend

when I open documents, neither google documents creation date nor metadata table creation date matches the sorting order

thoughts ?

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Your right, at first it seemed right but it was mostly lucky old ones at the top. I believe it's due to us sorting but a string not a date. For example, `"created": "12 May 2023"`.

We probably stringify it for ease in rendering but should be `formatted_date`

**Comment by beliaev-maksim** [comment]
@anthonydillon actually, it is a Date type
https://github.com/canonical/specs.canonical.com/blob/a55ff9417d8f8d260fd428d38a51b2199ffc3e31/client/types.ts#L11

and here:
https://github.com/canonical/specs.canonical.com/blob/a55ff9417d8f8d260fd428d38a51b2199ffc3e31/client/App.tsx#L30

I get it now. We trimmed the part with hours and minutes, that is why the accuracy is up to the day. I did a comparison with google sheet  and it is correct.

what is the place where we can adjust the accuracy for the date formatting ?

**Comment by beliaev-maksim** [comment]
@anthonydillon I added hours and minutes, now it is sorting precisely

**Review by anthonydillon — APPROVED** [review]
QA and code looks good to me. Checked about 10 specs and they were in the correct order.

**Pull request merged**
