### PR TITLE
feat: add a new spec link to docs

### LINKED ISSUE #25: Guide to create a spec
We should add a guide and maybe a button to copy the spec template to the correct team directory.

### PR DESCRIPTION
**Pull request by petermakowski**
## Done
- add a new spec with a link to docs

Fixes: https://github.com/canonical/specs.canonical.com/issues/25

## QA steps
- Click the "Add a new spec" link
- Verify it links to the google docs guide document

## Screenshots
image

### CODE REVIEW

**Comment by andesol** [comment]
Thanks @petermakowski! Happy to approve it, I only wonder if it isn't a bit confusing that the text says "Add a new spec". I would expect a form or similar, but it links to the guidelines. Shouldn't it say something like "Spec guidelines"? Unless it's obvious that the way to create a spec is duplicating the guidelines doc...

**Comment by petermakowski** [comment]
> Thanks @petermakowski! Happy to approve it, I only wonder if it isn't a bit confusing that the text says "Add a new spec". I would expect a form or similar, but it links to the guidelines. Shouldn't it say something like "Spec guidelines"? Unless it's obvious that the way to create a spec is duplicating the guidelines doc...

I don't think it is confusing, It links to the instructions how to create a spec where that's detailed. I do think it's a good label for a call to action button and it's encouraging.
It can (and should!) be replaced with a real form in the future. 

If you feel strongly about this, what about "How to add a new spec" instead of "Spec guidelines"?

**Comment by petermakowski** [comment]
@andesol Oh, but I think I see what you mean, someone might think that they're meant to edit the document that's just been opened. OK, I agree, let's rename.

**Comment by andesol** [comment]
I guess "Add a new spec" made me think of a quick action, rather than a document about how (and why) to write them. Maybe it's just me.

Let's try with "How to...". Thanks @petermakowski :rocket:

**Review by andesol — APPROVED** [review]

**Pull request merged**
