### PR TITLE
Added docker build env defaults

### PR DESCRIPTION
**Pull request by samhotep**
## Done
- Moved the build_specs command to after env variables have been set
- Increased memory limits to account for sheets loaded into memory

## QA
- Check that the demo build on jenkins completes successfully

### CODE REVIEW

**Comment by andesol** [comment]
@samhotep Didn't work. This site is a bit different because we execute a command at build time, so it may not work with the usual demo workflow? See [jenkins job](https://jenkins.canonical.com/webteam/view/Workplace/job/specs.canonical.com/configure)

**Comment by samhotep** [comment]
> @samhotep Didn't work. This site is a bit different because we execute a command at build time, so it may not work with the usual demo workflow? See [jenkins job](https://jenkins.canonical.com/webteam/view/Workplace/job/specs.canonical.com/configure)

I've noticed.. I've made some changes - let's see if it takes

**Comment by andesol** [comment]
Thanks for looking into this @samhotep!

The reason why the json file is generated at built time is for specs.c.c to be deployed with the specs ready to be displayed, without having to read the spreadsheet at run time. It was supposed to be a quick fix, so I haven't really explored all the possibilities. 

With this setup, what would happen if the json file fails to be generated? Will k8s keep the old pods, or rather the website will fail to go live? (Maybe it's so unlikely that is not even worth thinking about it).

**Comment by samhotep** [comment]
> Thanks for looking into this @samhotep!
> 
> The reason why the json file is generated at built time is for specs.c.c to be deployed with the specs ready to be displayed, without having to read the spreadsheet at run time. It was supposed to be a quick fix, so I haven't really explored all the possibilities.
> 
> With this setup, what would happen if the json file fails to be generated? Will k8s keep the old pods, or rather the website will fail to go live? (Maybe it's so unlikely that is not even worth thinking about it).

Yeah, in k8s if the pod startup doesn't succeed it won't delete the old pods. In Jenkins the deployment job will stall and eventually fail so we'd have to fix the issue before the site goes live.

**Review by andesol — APPROVED** [review]
That's much easier then, thanks!

**Pull request merged**
